### ISSUE TITLE
Reference Bug

### ISSUE THREAD

**Issue by VARFynn** [Nicktz/Texevier#6]
Hi Nico, 

I used your package (Februar 2024, Version) in the past and it worked wonderful -- Thank you for creating it. However, when installing it to a new windows device today, it shows unusual citation behavior, as it adds "code " after every year: 

![Bug_tex](https://github.com/user-attachments/assets/c2379038-f75a-48ce-98a7-6ffdc0593aae)

HTML Rendering works perfectly fine. So, I assume its stemming from the tex compilation. My usual tex compilations work perfectly fine. Thus, I assume it stems from the TexDefault.txt and

```
 \NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
\begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
```

Yet, it is still a guess and I let you know If I figured out the issue. 

Best,
Fynn Lohre

**Comment by VARFynn** [comment]
So when changing it to

```
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
\href{\#cite.\detokenize{#1}}{#2}\nocite{#1}}
```

I get my desired result:

![image](https://github.com/user-attachments/assets/fcfed610-2b5f-48af-b291-5781c2045581)

use

`[@fama1997; @grinold2000]` for double cite

**Comment by VARFynn** [comment]
Actually made a mistake:

```
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{m}{%
  \begingroup
  \def\do##1{\href{\#cite.\detokenize{##1}}{\nocite{##1}}}%
  (\docsvlist{#1})%
  \endgroup
}
```
and then 

` [@fama1997; @grinold2000]`

to get the together citation correct

**Comment by Nicktz** [comment]
Hi Fynn,

Thanks for identifying the problem and reaching out! It's a LaTeX issue - upstream package changes periodically cause problems like this.
I've now added your code to the package's Tex template, so if you redownload it your updated code will be in there.

Thanks,

Nico
